version: "3.8"

services:
  tips-app:
    build: .
    container_name: tips-app
    ports:
      - "${PORT}:${PORT}"
    expose:
      - "${PORT}"
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tips.rule=Host(`${DOMAIN_NAME}`) && PathPrefix(`/precheck`)"
      - "traefik.http.routers.tips.entrypoints=websecure"
      - "traefik.http.routers.tips.tls=true"
      - "traefik.http.routers.tips.tls.certresolver=le"
      - "traefik.http.routers.tips.priority=1"
      - "traefik.http.services.tips.loadbalancer.server.port=${PORT}"
      - "traefik.http.routers.tips-http.rule=Host(`${DOMAIN_NAME}`) && PathPrefix(`/precheck`)"
      - "traefik.http.routers.tips-http.entrypoints=web"
      - "traefik.http.routers.tips-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    restart: unless-stopped
networks:
  web:
    external: true
    name: web